/*
 * This file is generated by jOOQ.
 */
package com.br.sp.posgresdocker.model.jooq.pg_catalog.routines;


import com.br.sp.posgresdocker.model.jooq.pg_catalog.PgCatalog;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatePli extends AbstractRoutine<LocalDate> {

    private static final long serialVersionUID = -1419341023;

    /**
     * The parameter <code>pg_catalog.date_pli.RETURN_VALUE</code>.
     */
    public static final Parameter<LocalDate> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>pg_catalog.date_pli._1</code>.
     */
    public static final Parameter<LocalDate> _1 = createParameter("_1", org.jooq.impl.SQLDataType.LOCALDATE, false, true);

    /**
     * The parameter <code>pg_catalog.date_pli._2</code>.
     */
    public static final Parameter<Integer> _2 = createParameter("_2", org.jooq.impl.SQLDataType.INTEGER, false, true);

    /**
     * Create a new routine call instance
     */
    public DatePli() {
        super("date_pli", PgCatalog.PG_CATALOG, org.jooq.impl.SQLDataType.LOCALDATE);

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
        addInParameter(_2);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(LocalDate value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<LocalDate> field) {
        setField(_1, field);
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    public void set__2(Integer value) {
        setValue(_2, value);
    }

    /**
     * Set the <code>_2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__2(Field<Integer> field) {
        setField(_2, field);
    }
}
