/*
 * This file is generated by jOOQ.
 */
package com.br.sp.posgresdocker.model.jooq.pg_catalog.routines;


import com.br.sp.posgresdocker.model.jooq.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgReplicationOriginSessionReset extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1925832163;

    /**
     * Create a new routine call instance
     */
    public PgReplicationOriginSessionReset() {
        super("pg_replication_origin_session_reset", PgCatalog.PG_CATALOG);
    }
}
